export type CampingRegion = "Skåne" | "Småland" | "Blekinge";
export type CampingCategory = "Familj" | "Natur" | "Strand" | "Sjö" | "Stad" | "Äventyr";

export interface Campsite {
  id: string;
  slug: string;
  name: string;
  region: CampingRegion;
  municipality: string;
  category: CampingCategory;
  priceFrom: number;
  image: string;
  description: string;
  description_en: string;
  description_de: string;
  amenities: string[];
  rating: number;
  reviews: number;
  sourceUrl: string;
}

export const CAMPSITES: Campsite[] = [
  // SKÅNE
  {
    id: "c1",
    slug: "lomma-strandbad-camping",
    name: "Lomma Strandbad Camping",
    region: "Skåne",
    municipality: "Lomma",
    category: "Strand",
    priceFrom: 295,
    image: "https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800&q=80",
    description: "Fantastisk strandcamping med direkt tillgång till Öresund. Perfekt för familjer med barn.",
    description_en: "Fantastic beach camping with direct access to the Øresund strait. Perfect for families.",
    description_de: "Fantastischer Strandcampingplatz mit direktem Zugang zum Öresund. Ideal für Familien.",
    amenities: ["Strand", "Dusch", "Restaurang", "Lekplats", "WiFi"],
    rating: 8.9,
    reviews: 312,
    sourceUrl: "https://www.campcation.com/campings/lomma",
  },
  {
    id: "c2",
    slug: "ystad-sandskog-camping",
    name: "Ystad Sandskog Camping",
    region: "Skåne",
    municipality: "Ystad",
    category: "Natur",
    priceFrom: 275,
    image: "https://images.unsplash.com/photo-1537225228614-56cc3556d7ed?w=800&q=80",
    description: "Belägen i en vacker tallskog nära Ystad centrum och Östersjöns stränder.",
    description_en: "Located in a beautiful pine forest near Ystad city centre and the Baltic Sea beaches.",
    description_de: "In einem schönen Kiefernwald nahe der Innenstadt von Ystad und den Ostseeständen.",
    amenities: ["Skog", "Cykeluthyrning", "Dusch", "Kiosk"],
    rating: 8.5,
    reviews: 204,
    sourceUrl: "https://www.campcation.com/campings/ystad-sandskog",
  },
  {
    id: "c3",
    slug: "falsterbo-camping",
    name: "Falsterbo Camping",
    region: "Skåne",
    municipality: "Vellinge",
    category: "Strand",
    priceFrom: 320,
    image: "https://images.unsplash.com/photo-1510672981848-a1c4f1cb5ccf?w=800&q=80",
    description: "Sydsvenskt strandparadis på Falsterbohalvön. Perfekt för vindsurfing och fågelskådning.",
    description_en: "South Swedish beach paradise on the Falsterbo Peninsula. Perfect for windsurfing and birdwatching.",
    description_de: "Südschwestisches Strandparadies auf der Falsterbohalbinsel. Ideal für Windsurfen und Vogelbeobachtung.",
    amenities: ["Strand", "Surf", "Fågelskådning", "Dusch", "WiFi"],
    rating: 8.7,
    reviews: 178,
    sourceUrl: "https://www.campcation.com/campings/falsterbo",
  },
  {
    id: "c4",
    slug: "kristianstad-camping",
    name: "Kristianstad Camping",
    region: "Skåne",
    municipality: "Kristianstad",
    category: "Stad",
    priceFrom: 250,
    image: "https://images.unsplash.com/photo-1490682143684-14369e18dce8?w=800&q=80",
    description: "Centralt belägen camping vid Helge å, nära Kristianstads historiska centrum.",
    description_en: "Centrally located campsite by the Helge river, close to Kristianstad's historic city centre.",
    description_de: "Zentral gelegener Campingplatz am Fluss Helge, nahe der historischen Innenstadt von Kristianstad.",
    amenities: ["Å", "Cykelväg", "Dusch", "Restaurang"],
    rating: 8.2,
    reviews: 143,
    sourceUrl: "https://www.campcation.com/campings/kristianstad",
  },
  {
    id: "c5",
    slug: "helsingborg-camping",
    name: "Råå Vallar Camping",
    region: "Skåne",
    municipality: "Helsingborg",
    category: "Strand",
    priceFrom: 310,
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=800&q=80",
    description: "Populär strandcamping söder om Helsingborg med utsikt mot Danmark och Öresund.",
    description_en: "Popular beach campsite south of Helsingborg with views towards Denmark and the Øresund.",
    description_de: "Beliebter Strandcampingplatz südlich von Helsingborg mit Blick auf Dänemark und den Öresund.",
    amenities: ["Strand", "Vik", "Dusch", "Lekplats", "WiFi"],
    rating: 8.6,
    reviews: 267,
    sourceUrl: "https://www.campcation.com/campings/raa-vallar",
  },
  {
    id: "c6",
    slug: "bastad-camping",
    name: "Båstads Camping",
    region: "Skåne",
    municipality: "Båstad",
    category: "Natur",
    priceFrom: 285,
    image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&q=80",
    description: "Naturskön camping i Bjärehalvön, känd för sin tennis och pittoreska natur.",
    description_en: "Scenic camping on the Bjäre Peninsula, known for tennis and picturesque nature.",
    description_de: "Malerischer Campingplatz auf der Bjäre-Halbinsel, bekannt für Tennis und pittoreske Natur.",
    amenities: ["Natur", "Tennis", "Strand", "Dusch"],
    rating: 8.4,
    reviews: 156,
    sourceUrl: "https://www.campcation.com/campings/bastad",
  },

  // SMÅLAND
  {
    id: "c7",
    slug: "astrid-lindgrens-camping-vimmerby",
    name: "Vimmerby Camping",
    region: "Småland",
    municipality: "Vimmerby",
    category: "Familj",
    priceFrom: 265,
    image: "https://images.unsplash.com/photo-1533873984035-25970ab07461?w=800&q=80",
    description: "Familjecamping i Astrid Lindgrens hemstad. Perfekt läge nära Astrid Lindgrens Värld.",
    description_en: "Family camping in Astrid Lindgren's hometown. Perfect location near Astrid Lindgren's World.",
    description_de: "Familiencamping in Astrid Lindgrens Heimatstadt. Ideale Lage nahe Astrid Lindgrens Welt.",
    amenities: ["Lekplats", "Pool", "Dusch", "WiFi", "Kiosk"],
    rating: 8.8,
    reviews: 389,
    sourceUrl: "https://www.campcation.com/campings/vimmerby",
  },
  {
    id: "c8",
    slug: "vaxjo-sjostugan-camping",
    name: "Växjö Sjöstugan Camping",
    region: "Småland",
    municipality: "Växjö",
    category: "Sjö",
    priceFrom: 240,
    image: "https://images.unsplash.com/photo-1501854140801-50d01698950b?w=800&q=80",
    description: "Charmig camping vid Trummen mitt i glasriket. Kanotpaddling och bad ingår.",
    description_en: "Charming campsite at Lake Trummen in the Glass Kingdom. Canoeing and swimming included.",
    description_de: "Charmanter Campingplatz am See Trummen im Glasreich. Kanufahren und Schwimmen inklusive.",
    amenities: ["Sjö", "Kanot", "Bad", "Dusch", "WiFi"],
    rating: 8.6,
    reviews: 221,
    sourceUrl: "https://www.campcation.com/campings/vaxjo",
  },
  {
    id: "c9",
    slug: "jonkoping-rosenlund-camping",
    name: "Jönköping Rosenlunds Camping",
    region: "Småland",
    municipality: "Jönköping",
    category: "Sjö",
    priceFrom: 255,
    image: "https://images.unsplash.com/photo-1487730116645-74489c95b41b?w=800&q=80",
    description: "Strandcamping direkt vid Vättern med fantastisk utsikt. Nära Munksjön och centrum.",
    description_en: "Beach camping directly on Lake Vättern with fantastic views. Close to Munksjön and city centre.",
    description_de: "Strandcamping direkt am Vätternsee mit fantastischer Aussicht. Nahe Munksjön und Innenstadt.",
    amenities: ["Vättern", "Bad", "Båt", "Dusch", "Restaurang"],
    rating: 9.0,
    reviews: 445,
    sourceUrl: "https://www.campcation.com/campings/jonkoping-rosenlund",
  },
  {
    id: "c10",
    slug: "glasriket-camping-orrefors",
    name: "Glasriket Camping Orrefors",
    region: "Småland",
    municipality: "Nybro",
    category: "Natur",
    priceFrom: 220,
    image: "https://images.unsplash.com/photo-1540555700478-4be289fbecef?w=800&q=80",
    description: "Mitt i svenska glasriket. Besök berömda glashyttor och vandra i skogen.",
    description_en: "In the heart of Sweden's Glass Kingdom. Visit famous glassworks and hike through the forest.",
    description_de: "Im Herzen des schwedischen Glasreichs. Besuchen Sie berühmte Glashütten und wandern Sie im Wald.",
    amenities: ["Skog", "Vandring", "Glasbruk", "Dusch"],
    rating: 8.3,
    reviews: 134,
    sourceUrl: "https://www.campcation.com/campings/orrefors",
  },
  {
    id: "c11",
    slug: "kalmar-camping",
    name: "Kalmar Camping",
    region: "Småland",
    municipality: "Kalmar",
    category: "Stad",
    priceFrom: 270,
    image: "https://images.unsplash.com/photo-1508739773434-c26b3d09e071?w=800&q=80",
    description: "Strandcamping nära Kalmar slott och Ölandsbron. Utmärkt utgångspunkt för Öland.",
    description_en: "Beach camping near Kalmar Castle and the Öland Bridge. Excellent base for exploring Öland.",
    description_de: "Strandcamping nahe Schloss Kalmar und der Ölandbrücke. Ausgezeichneter Ausgangspunkt für Öland.",
    amenities: ["Strand", "Slott", "Cykel", "Dusch", "WiFi"],
    rating: 8.7,
    reviews: 298,
    sourceUrl: "https://www.campcation.com/campings/kalmar",
  },
  {
    id: "c12",
    slug: "eksjö-camping",
    name: "Eksjö Camping",
    region: "Småland",
    municipality: "Eksjö",
    category: "Äventyr",
    priceFrom: 230,
    image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?w=800&q=80",
    description: "Äventyrscamping i Höglandet med vandring, klättring och mountainbike.",
    description_en: "Adventure camping in the Highlands with hiking, climbing and mountain biking.",
    description_de: "Abenteuercamping im Hochland mit Wandern, Klettern und Mountainbiken.",
    amenities: ["Vandring", "Klättring", "MTB", "Dusch"],
    rating: 8.5,
    reviews: 167,
    sourceUrl: "https://www.campcation.com/campings/eksjo",
  },

  // BLEKINGE
  {
    id: "c13",
    slug: "karlskrona-saltö-camping",
    name: "Saltö Camping Karlskrona",
    region: "Blekinge",
    municipality: "Karlskrona",
    category: "Strand",
    priceFrom: 280,
    image: "https://images.unsplash.com/photo-1505118380757-91f5f5632de0?w=800&q=80",
    description: "Skärgårdscamping på ön Saltö utanför Karlskrona. UNESCO-världsarv inom gångavstånd.",
    description_en: "Archipelago camping on the island of Saltö outside Karlskrona. UNESCO World Heritage within walking distance.",
    description_de: "Schärencamping auf der Insel Saltö vor Karlskrona. UNESCO-Welterbe in Gehweite.",
    amenities: ["Skärgård", "Bad", "Båt", "Dusch", "Grill"],
    rating: 9.1,
    reviews: 356,
    sourceUrl: "https://www.campcation.com/campings/karlskrona-salto",
  },
  {
    id: "c14",
    slug: "ronneby-brunnspark-camping",
    name: "Ronneby Brunnspark Camping",
    region: "Blekinge",
    municipality: "Ronneby",
    category: "Natur",
    priceFrom: 245,
    image: "https://images.unsplash.com/photo-1448375240586-882707db888b?w=800&q=80",
    description: "Naturcamping i Ronneby Brunnspark — ett av Sveriges vackraste parkområden.",
    description_en: "Nature camping in Ronneby Brunnspark — one of Sweden's most beautiful park areas.",
    description_de: "Naturcamping im Ronneby Brunnspark — einer der schönsten Parkbereiche Schwedens.",
    amenities: ["Park", "Skog", "Å", "Dusch", "Vandring"],
    rating: 8.8,
    reviews: 212,
    sourceUrl: "https://www.campcation.com/campings/ronneby",
  },
  {
    id: "c15",
    slug: "karlshamn-camping",
    name: "Karlshamns Camping",
    region: "Blekinge",
    municipality: "Karlshamn",
    category: "Strand",
    priceFrom: 260,
    image: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=800&q=80",
    description: "Populär havscamping vid Karlshamn med direkttillgång till Östersjön.",
    description_en: "Popular seaside camping in Karlshamn with direct access to the Baltic Sea.",
    description_de: "Beliebter Meerscampingplatz in Karlshamn mit direktem Zugang zur Ostsee.",
    amenities: ["Hav", "Bad", "Strand", "Dusch", "WiFi"],
    rating: 8.6,
    reviews: 189,
    sourceUrl: "https://www.campcation.com/campings/karlshamn",
  },
  {
    id: "c16",
    slug: "olofstrom-camping",
    name: "Olofström Camping",
    region: "Blekinge",
    municipality: "Olofström",
    category: "Sjö",
    priceFrom: 210,
    image: "https://images.unsplash.com/photo-1532339142463-fd0a8979791a?w=800&q=80",
    description: "Fridfull sjöcamping vid Halen i Blekinge. Perfekt för paddling och fiske.",
    description_en: "Peaceful lake camping at Lake Halen in Blekinge. Perfect for paddling and fishing.",
    description_de: "Friedlicher Seecamping am Halensee in Blekinge. Ideal zum Paddeln und Angeln.",
    amenities: ["Sjö", "Fiske", "Kanot", "Dusch"],
    rating: 8.1,
    reviews: 98,
    sourceUrl: "https://www.campcation.com/campings/olofstrom",
  },
  {
    id: "c17",
    slug: "solvesborg-camping",
    name: "Sölvesborg Camping",
    region: "Blekinge",
    municipality: "Sölvesborg",
    category: "Familj",
    priceFrom: 255,
    image: "https://images.unsplash.com/photo-1478131143081-80f7f84ca84d?w=800&q=80",
    description: "Familjevänlig camping med barnpool, lekplats och strandnärhet i västra Blekinge.",
    description_en: "Family-friendly camping with children's pool, playground and beach access in western Blekinge.",
    description_de: "Familienfreundlicher Campingplatz mit Kinderpool, Spielplatz und Strandnähe in Westblekinge.",
    amenities: ["Pool", "Lekplats", "Strand", "Dusch", "Kiosk"],
    rating: 8.4,
    reviews: 231,
    sourceUrl: "https://www.campcation.com/campings/solvesborg",
  },
];

export const CAMPING_CATEGORIES: CampingCategory[] = ["Familj", "Natur", "Strand", "Sjö", "Stad", "Äventyr"];
export const CAMPING_REGIONS: CampingRegion[] = ["Skåne", "Småland", "Blekinge"];
